name : ci-lint

on:
  push:
    branches:
    - packer-1.4.2-ansible-2.8.1
  pull_request:
    branches:
    - packer-1.4.2-ansible-2.8.1

jobs:
  
  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
